project:
  type: book
  output-dir: "docs"
  preview:
    port: 1313
    browser: false

jupyter: julia-1.11

execute: 
  freeze: auto
  cache: true
  daemon: 3600
  warning: false
  message: false

website:
  favicon: "img/logos/favicon.ico"
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Pácticas de Aprendizaje Automático con R"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2024"
  output-file: "practicas-aprendizaje-automatico-r"
  image: img/logos/sticker.png
  cover-image: img/logos/sticker.png
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar: 
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  twitter-card: 
    site: "@aprendeconalf"
  chapters:
    - index.qmd
    - 01-introduccion.qmd
    - 02-preprocesamiento.qmd
    - 03-aprendizaje-no-supervisado.qmd
    - 04-regresion.qmd
    # - 05-k-vecinos.qmd
    # - 06-arboles-decision.qmd
    #- 09-redes-neuronales.qmd

#bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme:
      dark: darkly
      light: flatly
    html-math-method: mathjax
    default-image-extension: svg
    code-overflow: wrap
    toc: false
  pdf:
    documentclass: scrreport
    papersize: a4
    template-partials:
      - before-body.tex
    titlegraphic: img/logos/sticker.png
    institution: CEU San Pablo
    email: asalber@ceu.es
    web: https://aprendeconalf.es
    logo: img/logos/aprendeconalf.png
    include-in-header:
      - preamble.tex
      - macros.tex
    keep-tex: true
    #mainfont: TeX Gyre Termes
    #mainfontoptions:
    #  - Numbers=Lowercase
    #  - Numbers=Proportional    
    
  epub:
    cover-image: img/logos/sticker.png
    html-math-method: mathml
    toc: true



