---
lang: es
---

# Prefacio {.unnumbered}

¡Bienvenido a Prácticas de Aprendizaje Automático con R!

Este sitio presenta una recopilación de prácticas de Aprendizaje Automático (Machine Learning) con el lenguaje de programación [R](https://www.r-project.org/).

No es un sitio para aprender a programar con R, ya que solo enseña el uso del lenguaje y de algunos de sus paquetes para implementar los algoritmos más comunes de Aprendizaje Automático. Además, para poder realizar estas prácticas, es necesario tener un mínimo conocimiento de los tipos de datos y las funciones básicas de R, así como de los paquetes `dplyr`, para el preprocesamiento de datos, y `ggplot2`, para la visualización de datos. Para quienes estén interesados en aprender a programar en este lenguaje y conocer estos paquetes, os recomiendo leer este [manual de R](https://aprendeconalf.es/manual-r).

## Licencia

Esta obra está bajo una licencia Reconocimiento – No comercial – Compartir bajo la misma licencia 3.0 España de Creative Commons. Para ver una copia de esta licencia, visite [https://creativecommons.org/licenses/by-nc-sa/3.0/es/](https://creativecommons.org/licenses/by-nc-sa/3.0/es/).

Con esta licencia eres libre de:

- Copiar, distribuir y mostrar este trabajo.
- Realizar modificaciones de este trabajo.

Bajo las siguientes condiciones:

- **Reconocimiento**. Debe reconocer los créditos de la obra de la manera especificada por el autor o el licenciador (pero no de una manera que sugiera que tiene su apoyo o apoyan el uso que hace de su obra).

- **No comercial**. No puede utilizar esta obra para fines comerciales.

- **Compartir bajo la misma licencia**. Si altera o transforma esta obra, o genera una obra derivada, sólo puede distribuir la obra generada bajo una licencia idéntica a ésta.

Al reutilizar o distribuir la obra, tiene que dejar bien claro los términos de la licencia de esta obra.

Estas condiciones pueden no aplicarse si se obtiene el permiso del titular de los derechos de autor.

Nada en esta licencia menoscaba o restringe los derechos morales del autor.